# Generated by Django 3.0.6 on 2020-05-09 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funcionarios', '0004_auto_20200509_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
